#ifndef ITEMS_HPP_GENERATED
#define ITEMS_HPP_GENERATED

#include <map>

namespace dota2
{
    enum class Item
    {
        Unknown                                    = 0,
        Blink_Dagger                               = 1,
        Blades_of_Attack                           = 2,
        Broadsword                                 = 3,
        Chainmail                                  = 4,
        Claymore                                   = 5,
        Helm_of_Iron_Will                          = 6,
        Javelin                                    = 7,
        Mithril_Hammer                             = 8,
        Platemail                                  = 9,
        Quarterstaff                               = 10,
        Quelling_Blade                             = 11,
        Ring_of_Protection                         = 12,
        Gauntlets_of_Strength                      = 13,
        Slippers_of_Agility                        = 14,
        Mantle_of_Intelligence                     = 15,
        Iron_Branch                                = 16,
        Belt_of_Strength                           = 17,
        Band_of_Elvenskin                          = 18,
        Robe_of_the_Magi                           = 19,
        Circlet                                    = 20,
        Ogre_Club                                  = 21,
        Blade_of_Alacrity                          = 22,
        Staff_of_Wizardry                          = 23,
        Ultimate_Orb                               = 24,
        Gloves_of_Haste                            = 25,
        Morbid_Mask                                = 26,
        Ring_of_Regen                              = 27,
        Sages_Mask                                 = 28,
        Boots_of_Speed                             = 29,
        Gem_of_True_Sight                          = 30,
        Cloak                                      = 31,
        Talisman_of_Evasion                        = 32,
        Cheese                                     = 33,
        Magic_Stick                                = 34,
        Recipe_Magic_Wand                          = 35,
        Magic_Wand                                 = 36,
        Ghost_Scepter                              = 37,
        Clarity                                    = 38,
        Healing_Salve                              = 39,
        Dust_of_Appearance                         = 40,
        Bottle                                     = 41,
        Observer_Ward                              = 42,
        Sentry_Ward                                = 43,
        Tango                                      = 44,
        Animal_Courier                             = 45,
        Town_Portal_Scroll                         = 46,
        Recipe_Boots_of_Travel                     = 47,
        Boots_of_Travel                            = 48,
        Recipe_Phase_Boots                         = 49,
        Phase_Boots                                = 50,
        Demon_Edge                                 = 51,
        Eaglesong                                  = 52,
        Reaver                                     = 53,
        Sacred_Relic                               = 54,
        Hyperstone                                 = 55,
        Ring_of_Health                             = 56,
        Void_Stone                                 = 57,
        Mystic_Staff                               = 58,
        Energy_Booster                             = 59,
        Point_Booster                              = 60,
        Vitality_Booster                           = 61,
        Recipe_Power_Treads                        = 62,
        Power_Treads                               = 63,
        Recipe_Hand_of_Midas                       = 64,
        Hand_of_Midas                              = 65,
        Recipe_Oblivion_Staff                      = 66,
        Oblivion_Staff                             = 67,
        Recipe_Perseverance                        = 68,
        Perseverance                               = 69,
        Recipe_Poor_Mans_Shield                    = 70,
        Poor_Mans_Shield                           = 71,
        Recipe_Bracer                              = 72,
        Bracer                                     = 73,
        Recipe_Wraith_Band                         = 74,
        Wraith_Band                                = 75,
        Recipe_Null_Talisman                       = 76,
        Null_Talisman                              = 77,
        Recipe_Mekansm                             = 78,
        Mekansm                                    = 79,
        Recipe_Vladmirs_Offering                   = 80,
        Vladmirs_Offering                          = 81,
        Flying_Courier                             = 84,
        Recipe_Buckler                             = 85,
        Buckler                                    = 86,
        Recipe_Ring_of_Basilius                    = 87,
        Ring_of_Basilius                           = 88,
        Recipe_Pipe_of_Insight                     = 89,
        Pipe_of_Insight                            = 90,
        Recipe_Urn_of_Shadows                      = 91,
        Urn_of_Shadows                             = 92,
        Recipe_Headdress                           = 93,
        Headdress                                  = 94,
        Recipe_Scythe_of_Vyse                      = 95,
        Scythe_of_Vyse                             = 96,
        Recipe_Orchid_Malevolence                  = 97,
        Orchid_Malevolence                         = 98,
        Recipe_Euls_Scepter_of_Divinity            = 99,
        Euls_Scepter_of_Divinity                   = 100,
        Recipe_Force_Staff                         = 101,
        Force_Staff                                = 102,
        Recipe_Dagon                               = 103,
        Dagon                                      = 104,
        Recipe_Necronomicon                        = 105,
        Necronomicon                               = 106,
        Recipe_Aghanims_Scepter                    = 107,
        Aghanims_Scepter                           = 108,
        Recipe_Refresher_Orb                       = 109,
        Refresher_Orb                              = 110,
        Recipe_Assault_Cuirass                     = 111,
        Assault_Cuirass                            = 112,
        Recipe_Heart_of_Tarrasque                  = 113,
        Heart_of_Tarrasque                         = 114,
        Recipe_Black_King_Bar                      = 115,
        Black_King_Bar                             = 116,
        Aegis_of_the_Immortal                      = 117,
        Recipe_Shivas_Guard                        = 118,
        Shivas_Guard                               = 119,
        Recipe_Bloodstone                          = 120,
        Bloodstone                                 = 121,
        Recipe_Linkens_Sphere                      = 122,
        Linkens_Sphere                             = 123,
        Recipe_Vanguard                            = 124,
        Vanguard                                   = 125,
        Recipe_Blade_Mail                          = 126,
        Blade_Mail                                 = 127,
        Recipe_Soul_Booster                        = 128,
        Soul_Booster                               = 129,
        Recipe_Hood_of_Defiance                    = 130,
        Hood_of_Defiance                           = 131,
        Recipe_Divine_Rapier                       = 132,
        Divine_Rapier                              = 133,
        Recipe_Monkey_King_Bar                     = 134,
        Monkey_King_Bar                            = 135,
        Recipe_Radiance                            = 136,
        Radiance                                   = 137,
        Recipe_Butterfly                           = 138,
        Butterfly                                  = 139,
        Recipe_Daedalus                            = 140,
        Daedalus                                   = 141,
        Recipe_Skull_Basher                        = 142,
        Skull_Basher                               = 143,
        Recipe_Battle_Fury                         = 144,
        Battle_Fury                                = 145,
        Recipe_Manta_Style                         = 146,
        Manta_Style                                = 147,
        Recipe_Crystalys                           = 148,
        Crystalys                                  = 149,
        Recipe_Armlet_of_Mordiggian                = 150,
        Armlet_of_Mordiggian                       = 151,
        Shadow_Blade                               = 152,
        Recipe_Sange_and_Yasha                     = 153,
        Sange_and_Yasha                            = 154,
        Recipe_Satanic                             = 155,
        Satanic                                    = 156,
        Recipe_Mjollnir                            = 157,
        Mjollnir                                   = 158,
        Recipe_Eye_of_Skadi                        = 159,
        Eye_of_Skadi                               = 160,
        Recipe_Sange                               = 161,
        Sange                                      = 162,
        Recipe_Helm_of_the_Dominator               = 163,
        Helm_of_the_Dominator                      = 164,
        Recipe_Maelstrom                           = 165,
        Maelstrom                                  = 166,
        Recipe_Desolator                           = 167,
        Desolator                                  = 168,
        Recipe_Yasha                               = 169,
        Yasha                                      = 170,
        Recipe_Mask_of_Madness                     = 171,
        Mask_of_Madness                            = 172,
        Recipe_Diffusal_Blade                      = 173,
        Diffusal_Blade                             = 174,
        Recipe_Ethereal_Blade                      = 175,
        Ethereal_Blade                             = 176,
        Recipe_Soul_Ring                           = 177,
        Soul_Ring                                  = 178,
        Recipe_Arcane_Boots                        = 179,
        Arcane_Boots                               = 180,
        Orb_of_Venom                               = 181,
        Stout_Shield                               = 182,
        Recipe_Shadow_Blade                        = 183,
        Recipe_Drum_of_Endurance                   = 184,
        Drum_of_Endurance                          = 185,
        Recipe_Medallion_of_Courage                = 186,
        Medallion_of_Courage                       = 187,
        Smoke_of_Deceit                            = 188,
        Recipe_Veil_of_Discord                     = 189,
        Veil_of_Discord                            = 190,
        Recipe_Necronomicon2                       = 191,
        Recipe_Necronomicon3                       = 192,
        Necronomicon2                              = 193,
        Necronomicon3                              = 194,
        Recipe_Diffusal_Blade2                     = 195,
        Diffusal_Blade2                            = 196,
        Recipe_Dagon2                              = 197,
        Recipe_Dagon3                              = 198,
        Recipe_Dagon4                              = 199,
        Recipe_Dagon5                              = 200,
        Dagon2                                     = 201,
        Dagon3                                     = 202,
        Dagon4                                     = 203,
        Dagon5                                     = 204,
        Recipe_Rod_of_Atos                         = 205,
        Rod_of_Atos                                = 206,
        Recipe_Abyssal_Blade                       = 207,
        Abyssal_Blade                              = 208,
        Recipe_Heavens_Halberd                     = 209,
        Heavens_Halberd                            = 210,
        Recipe_Ring_of_Aquila                      = 211,
        Ring_of_Aquila                             = 212,
        Recipe_Tranquil_Boots                      = 213,
        Tranquil_Boots                             = 214,
        Shadow_Amulet                              = 215,
        Enchanted_Mango                            = 216,
        Recipe_Observer_and_Sentry_Wards           = 217,
        Observer_and_Sentry_Wards                  = 218,
        Recipe_Boots_of_Travel2                    = 219,
        Boots_of_Travel2                           = 220,
        Recipe_Lotus_Orb                           = 221,
        Lotus_Orb                                  = 226,
        Recipe_Solar_Crest                         = 227,
        Recipe_Octarine_Core                       = 228,
        Solar_Crest                                = 229,
        Recipe_Guardian_Greaves                    = 230,
        Guardian_Greaves                           = 231,
        Aether_Lens                                = 232,
        Recipe_Aether_Lens                         = 233,
        Recipe_Dragon_Lance                        = 234,
        Octarine_Core                              = 235,
        Dragon_Lance                               = 236,
        Faerie_Fire                                = 237,
        Recipe_Iron_Talon                          = 238,
        Iron_Talon                                 = 239,
        Tango_Shared                               = 241,
        Crimson_Guard                              = 242,
        Recipe_Crimson_Guard                       = 243,
        Recipe_Moon_Shard                          = 246,
        Moon_Shard                                 = 247,
        Recipe_Silver_Edge                         = 248,
        Silver_Edge                                = 249,
        Recipe_Glimmer_Cape                        = 253,
        Glimmer_Cape                               = 254,
        Greevil_Taffy                              = 1000,
        DOTA_Tooltip_Ability_item_mystery_hook     = 1001,
        DOTA_Tooltip_Ability_item_mystery_arrow    = 1002,
        DOTA_Tooltip_Ability_item_mystery_missile  = 1003,
        DOTA_Tooltip_Ability_item_mystery_toss     = 1004,
        DOTA_Tooltip_Ability_item_mystery_vacuum   = 1005,
        DOTA_Tooltip_Ability_item_halloween_rapier = 1006,
        Greevil_Whistle                            = 1007,
        Greevil_Whistle2                           = 1008,
        A_Gift                                     = 1009,
        Xmas_Stocking                              = 1010,
        Speed_Skates                               = 1011,
        Fruit_bit_Cake                             = 1012,
        Wizard_Cookie                              = 1013,
        Cocoa_with_Marshmallows                    = 1014,
        Clove_Studded_Ham                          = 1015,
        Kringle                                    = 1016,
        Snow_Mushroom                              = 1017,
        Greevil_Treat                              = 1018,
        Greevil_Chow                               = 1019,
        Greevil_Blink_Bone                         = 1020,
    };

    const std::map<int, Item> items({
        {(int)Item::Unknown, Item::Unknown},
        {(int)Item::Blink_Dagger, Item::Blink_Dagger},
        {(int)Item::Blades_of_Attack, Item::Blades_of_Attack},
        {(int)Item::Broadsword, Item::Broadsword},
        {(int)Item::Chainmail, Item::Chainmail},
        {(int)Item::Claymore, Item::Claymore},
        {(int)Item::Helm_of_Iron_Will, Item::Helm_of_Iron_Will},
        {(int)Item::Javelin, Item::Javelin},
        {(int)Item::Mithril_Hammer, Item::Mithril_Hammer},
        {(int)Item::Platemail, Item::Platemail},
        {(int)Item::Quarterstaff, Item::Quarterstaff},
        {(int)Item::Quelling_Blade, Item::Quelling_Blade},
        {(int)Item::Ring_of_Protection, Item::Ring_of_Protection},
        {(int)Item::Gauntlets_of_Strength, Item::Gauntlets_of_Strength},
        {(int)Item::Slippers_of_Agility, Item::Slippers_of_Agility},
        {(int)Item::Mantle_of_Intelligence, Item::Mantle_of_Intelligence},
        {(int)Item::Iron_Branch, Item::Iron_Branch},
        {(int)Item::Belt_of_Strength, Item::Belt_of_Strength},
        {(int)Item::Band_of_Elvenskin, Item::Band_of_Elvenskin},
        {(int)Item::Robe_of_the_Magi, Item::Robe_of_the_Magi},
        {(int)Item::Circlet, Item::Circlet},
        {(int)Item::Ogre_Club, Item::Ogre_Club},
        {(int)Item::Blade_of_Alacrity, Item::Blade_of_Alacrity},
        {(int)Item::Staff_of_Wizardry, Item::Staff_of_Wizardry},
        {(int)Item::Ultimate_Orb, Item::Ultimate_Orb},
        {(int)Item::Gloves_of_Haste, Item::Gloves_of_Haste},
        {(int)Item::Morbid_Mask, Item::Morbid_Mask},
        {(int)Item::Ring_of_Regen, Item::Ring_of_Regen},
        {(int)Item::Sages_Mask, Item::Sages_Mask},
        {(int)Item::Boots_of_Speed, Item::Boots_of_Speed},
        {(int)Item::Gem_of_True_Sight, Item::Gem_of_True_Sight},
        {(int)Item::Cloak, Item::Cloak},
        {(int)Item::Talisman_of_Evasion, Item::Talisman_of_Evasion},
        {(int)Item::Cheese, Item::Cheese},
        {(int)Item::Magic_Stick, Item::Magic_Stick},
        {(int)Item::Recipe_Magic_Wand, Item::Recipe_Magic_Wand},
        {(int)Item::Magic_Wand, Item::Magic_Wand},
        {(int)Item::Ghost_Scepter, Item::Ghost_Scepter},
        {(int)Item::Clarity, Item::Clarity},
        {(int)Item::Healing_Salve, Item::Healing_Salve},
        {(int)Item::Dust_of_Appearance, Item::Dust_of_Appearance},
        {(int)Item::Bottle, Item::Bottle},
        {(int)Item::Observer_Ward, Item::Observer_Ward},
        {(int)Item::Sentry_Ward, Item::Sentry_Ward},
        {(int)Item::Tango, Item::Tango},
        {(int)Item::Animal_Courier, Item::Animal_Courier},
        {(int)Item::Town_Portal_Scroll, Item::Town_Portal_Scroll},
        {(int)Item::Recipe_Boots_of_Travel, Item::Recipe_Boots_of_Travel},
        {(int)Item::Boots_of_Travel, Item::Boots_of_Travel},
        {(int)Item::Recipe_Phase_Boots, Item::Recipe_Phase_Boots},
        {(int)Item::Phase_Boots, Item::Phase_Boots},
        {(int)Item::Demon_Edge, Item::Demon_Edge},
        {(int)Item::Eaglesong, Item::Eaglesong},
        {(int)Item::Reaver, Item::Reaver},
        {(int)Item::Sacred_Relic, Item::Sacred_Relic},
        {(int)Item::Hyperstone, Item::Hyperstone},
        {(int)Item::Ring_of_Health, Item::Ring_of_Health},
        {(int)Item::Void_Stone, Item::Void_Stone},
        {(int)Item::Mystic_Staff, Item::Mystic_Staff},
        {(int)Item::Energy_Booster, Item::Energy_Booster},
        {(int)Item::Point_Booster, Item::Point_Booster},
        {(int)Item::Vitality_Booster, Item::Vitality_Booster},
        {(int)Item::Recipe_Power_Treads, Item::Recipe_Power_Treads},
        {(int)Item::Power_Treads, Item::Power_Treads},
        {(int)Item::Recipe_Hand_of_Midas, Item::Recipe_Hand_of_Midas},
        {(int)Item::Hand_of_Midas, Item::Hand_of_Midas},
        {(int)Item::Recipe_Oblivion_Staff, Item::Recipe_Oblivion_Staff},
        {(int)Item::Oblivion_Staff, Item::Oblivion_Staff},
        {(int)Item::Recipe_Perseverance, Item::Recipe_Perseverance},
        {(int)Item::Perseverance, Item::Perseverance},
        {(int)Item::Recipe_Poor_Mans_Shield, Item::Recipe_Poor_Mans_Shield},
        {(int)Item::Poor_Mans_Shield, Item::Poor_Mans_Shield},
        {(int)Item::Recipe_Bracer, Item::Recipe_Bracer},
        {(int)Item::Bracer, Item::Bracer},
        {(int)Item::Recipe_Wraith_Band, Item::Recipe_Wraith_Band},
        {(int)Item::Wraith_Band, Item::Wraith_Band},
        {(int)Item::Recipe_Null_Talisman, Item::Recipe_Null_Talisman},
        {(int)Item::Null_Talisman, Item::Null_Talisman},
        {(int)Item::Recipe_Mekansm, Item::Recipe_Mekansm},
        {(int)Item::Mekansm, Item::Mekansm},
        {(int)Item::Recipe_Vladmirs_Offering, Item::Recipe_Vladmirs_Offering},
        {(int)Item::Vladmirs_Offering, Item::Vladmirs_Offering},
        {(int)Item::Flying_Courier, Item::Flying_Courier},
        {(int)Item::Recipe_Buckler, Item::Recipe_Buckler},
        {(int)Item::Buckler, Item::Buckler},
        {(int)Item::Recipe_Ring_of_Basilius, Item::Recipe_Ring_of_Basilius},
        {(int)Item::Ring_of_Basilius, Item::Ring_of_Basilius},
        {(int)Item::Recipe_Pipe_of_Insight, Item::Recipe_Pipe_of_Insight},
        {(int)Item::Pipe_of_Insight, Item::Pipe_of_Insight},
        {(int)Item::Recipe_Urn_of_Shadows, Item::Recipe_Urn_of_Shadows},
        {(int)Item::Urn_of_Shadows, Item::Urn_of_Shadows},
        {(int)Item::Recipe_Headdress, Item::Recipe_Headdress},
        {(int)Item::Headdress, Item::Headdress},
        {(int)Item::Recipe_Scythe_of_Vyse, Item::Recipe_Scythe_of_Vyse},
        {(int)Item::Scythe_of_Vyse, Item::Scythe_of_Vyse},
        {(int)Item::Recipe_Orchid_Malevolence, Item::Recipe_Orchid_Malevolence},
        {(int)Item::Orchid_Malevolence, Item::Orchid_Malevolence},
        {(int)Item::Recipe_Euls_Scepter_of_Divinity,
         Item::Recipe_Euls_Scepter_of_Divinity},
        {(int)Item::Euls_Scepter_of_Divinity, Item::Euls_Scepter_of_Divinity},
        {(int)Item::Recipe_Force_Staff, Item::Recipe_Force_Staff},
        {(int)Item::Force_Staff, Item::Force_Staff},
        {(int)Item::Recipe_Dagon, Item::Recipe_Dagon},
        {(int)Item::Dagon, Item::Dagon},
        {(int)Item::Recipe_Necronomicon, Item::Recipe_Necronomicon},
        {(int)Item::Necronomicon, Item::Necronomicon},
        {(int)Item::Recipe_Aghanims_Scepter, Item::Recipe_Aghanims_Scepter},
        {(int)Item::Aghanims_Scepter, Item::Aghanims_Scepter},
        {(int)Item::Recipe_Refresher_Orb, Item::Recipe_Refresher_Orb},
        {(int)Item::Refresher_Orb, Item::Refresher_Orb},
        {(int)Item::Recipe_Assault_Cuirass, Item::Recipe_Assault_Cuirass},
        {(int)Item::Assault_Cuirass, Item::Assault_Cuirass},
        {(int)Item::Recipe_Heart_of_Tarrasque, Item::Recipe_Heart_of_Tarrasque},
        {(int)Item::Heart_of_Tarrasque, Item::Heart_of_Tarrasque},
        {(int)Item::Recipe_Black_King_Bar, Item::Recipe_Black_King_Bar},
        {(int)Item::Black_King_Bar, Item::Black_King_Bar},
        {(int)Item::Aegis_of_the_Immortal, Item::Aegis_of_the_Immortal},
        {(int)Item::Recipe_Shivas_Guard, Item::Recipe_Shivas_Guard},
        {(int)Item::Shivas_Guard, Item::Shivas_Guard},
        {(int)Item::Recipe_Bloodstone, Item::Recipe_Bloodstone},
        {(int)Item::Bloodstone, Item::Bloodstone},
        {(int)Item::Recipe_Linkens_Sphere, Item::Recipe_Linkens_Sphere},
        {(int)Item::Linkens_Sphere, Item::Linkens_Sphere},
        {(int)Item::Recipe_Vanguard, Item::Recipe_Vanguard},
        {(int)Item::Vanguard, Item::Vanguard},
        {(int)Item::Recipe_Blade_Mail, Item::Recipe_Blade_Mail},
        {(int)Item::Blade_Mail, Item::Blade_Mail},
        {(int)Item::Recipe_Soul_Booster, Item::Recipe_Soul_Booster},
        {(int)Item::Soul_Booster, Item::Soul_Booster},
        {(int)Item::Recipe_Hood_of_Defiance, Item::Recipe_Hood_of_Defiance},
        {(int)Item::Hood_of_Defiance, Item::Hood_of_Defiance},
        {(int)Item::Recipe_Divine_Rapier, Item::Recipe_Divine_Rapier},
        {(int)Item::Divine_Rapier, Item::Divine_Rapier},
        {(int)Item::Recipe_Monkey_King_Bar, Item::Recipe_Monkey_King_Bar},
        {(int)Item::Monkey_King_Bar, Item::Monkey_King_Bar},
        {(int)Item::Recipe_Radiance, Item::Recipe_Radiance},
        {(int)Item::Radiance, Item::Radiance},
        {(int)Item::Recipe_Butterfly, Item::Recipe_Butterfly},
        {(int)Item::Butterfly, Item::Butterfly},
        {(int)Item::Recipe_Daedalus, Item::Recipe_Daedalus},
        {(int)Item::Daedalus, Item::Daedalus},
        {(int)Item::Recipe_Skull_Basher, Item::Recipe_Skull_Basher},
        {(int)Item::Skull_Basher, Item::Skull_Basher},
        {(int)Item::Recipe_Battle_Fury, Item::Recipe_Battle_Fury},
        {(int)Item::Battle_Fury, Item::Battle_Fury},
        {(int)Item::Recipe_Manta_Style, Item::Recipe_Manta_Style},
        {(int)Item::Manta_Style, Item::Manta_Style},
        {(int)Item::Recipe_Crystalys, Item::Recipe_Crystalys},
        {(int)Item::Crystalys, Item::Crystalys},
        {(int)Item::Recipe_Armlet_of_Mordiggian,
         Item::Recipe_Armlet_of_Mordiggian},
        {(int)Item::Armlet_of_Mordiggian, Item::Armlet_of_Mordiggian},
        {(int)Item::Shadow_Blade, Item::Shadow_Blade},
        {(int)Item::Recipe_Sange_and_Yasha, Item::Recipe_Sange_and_Yasha},
        {(int)Item::Sange_and_Yasha, Item::Sange_and_Yasha},
        {(int)Item::Recipe_Satanic, Item::Recipe_Satanic},
        {(int)Item::Satanic, Item::Satanic},
        {(int)Item::Recipe_Mjollnir, Item::Recipe_Mjollnir},
        {(int)Item::Mjollnir, Item::Mjollnir},
        {(int)Item::Recipe_Eye_of_Skadi, Item::Recipe_Eye_of_Skadi},
        {(int)Item::Eye_of_Skadi, Item::Eye_of_Skadi},
        {(int)Item::Recipe_Sange, Item::Recipe_Sange},
        {(int)Item::Sange, Item::Sange},
        {(int)Item::Recipe_Helm_of_the_Dominator,
         Item::Recipe_Helm_of_the_Dominator},
        {(int)Item::Helm_of_the_Dominator, Item::Helm_of_the_Dominator},
        {(int)Item::Recipe_Maelstrom, Item::Recipe_Maelstrom},
        {(int)Item::Maelstrom, Item::Maelstrom},
        {(int)Item::Recipe_Desolator, Item::Recipe_Desolator},
        {(int)Item::Desolator, Item::Desolator},
        {(int)Item::Recipe_Yasha, Item::Recipe_Yasha},
        {(int)Item::Yasha, Item::Yasha},
        {(int)Item::Recipe_Mask_of_Madness, Item::Recipe_Mask_of_Madness},
        {(int)Item::Mask_of_Madness, Item::Mask_of_Madness},
        {(int)Item::Recipe_Diffusal_Blade, Item::Recipe_Diffusal_Blade},
        {(int)Item::Diffusal_Blade, Item::Diffusal_Blade},
        {(int)Item::Recipe_Ethereal_Blade, Item::Recipe_Ethereal_Blade},
        {(int)Item::Ethereal_Blade, Item::Ethereal_Blade},
        {(int)Item::Recipe_Soul_Ring, Item::Recipe_Soul_Ring},
        {(int)Item::Soul_Ring, Item::Soul_Ring},
        {(int)Item::Recipe_Arcane_Boots, Item::Recipe_Arcane_Boots},
        {(int)Item::Arcane_Boots, Item::Arcane_Boots},
        {(int)Item::Orb_of_Venom, Item::Orb_of_Venom},
        {(int)Item::Stout_Shield, Item::Stout_Shield},
        {(int)Item::Recipe_Shadow_Blade, Item::Recipe_Shadow_Blade},
        {(int)Item::Recipe_Drum_of_Endurance, Item::Recipe_Drum_of_Endurance},
        {(int)Item::Drum_of_Endurance, Item::Drum_of_Endurance},
        {(int)Item::Recipe_Medallion_of_Courage,
         Item::Recipe_Medallion_of_Courage},
        {(int)Item::Medallion_of_Courage, Item::Medallion_of_Courage},
        {(int)Item::Smoke_of_Deceit, Item::Smoke_of_Deceit},
        {(int)Item::Recipe_Veil_of_Discord, Item::Recipe_Veil_of_Discord},
        {(int)Item::Veil_of_Discord, Item::Veil_of_Discord},
        {(int)Item::Recipe_Necronomicon2, Item::Recipe_Necronomicon2},
        {(int)Item::Recipe_Necronomicon3, Item::Recipe_Necronomicon3},
        {(int)Item::Necronomicon2, Item::Necronomicon2},
        {(int)Item::Necronomicon3, Item::Necronomicon3},
        {(int)Item::Recipe_Diffusal_Blade2, Item::Recipe_Diffusal_Blade2},
        {(int)Item::Diffusal_Blade2, Item::Diffusal_Blade2},
        {(int)Item::Recipe_Dagon2, Item::Recipe_Dagon2},
        {(int)Item::Recipe_Dagon3, Item::Recipe_Dagon3},
        {(int)Item::Recipe_Dagon4, Item::Recipe_Dagon4},
        {(int)Item::Recipe_Dagon5, Item::Recipe_Dagon5},
        {(int)Item::Dagon2, Item::Dagon2},
        {(int)Item::Dagon3, Item::Dagon3},
        {(int)Item::Dagon4, Item::Dagon4},
        {(int)Item::Dagon5, Item::Dagon5},
        {(int)Item::Recipe_Rod_of_Atos, Item::Recipe_Rod_of_Atos},
        {(int)Item::Rod_of_Atos, Item::Rod_of_Atos},
        {(int)Item::Recipe_Abyssal_Blade, Item::Recipe_Abyssal_Blade},
        {(int)Item::Abyssal_Blade, Item::Abyssal_Blade},
        {(int)Item::Recipe_Heavens_Halberd, Item::Recipe_Heavens_Halberd},
        {(int)Item::Heavens_Halberd, Item::Heavens_Halberd},
        {(int)Item::Recipe_Ring_of_Aquila, Item::Recipe_Ring_of_Aquila},
        {(int)Item::Ring_of_Aquila, Item::Ring_of_Aquila},
        {(int)Item::Recipe_Tranquil_Boots, Item::Recipe_Tranquil_Boots},
        {(int)Item::Tranquil_Boots, Item::Tranquil_Boots},
        {(int)Item::Shadow_Amulet, Item::Shadow_Amulet},
        {(int)Item::Enchanted_Mango, Item::Enchanted_Mango},
        {(int)Item::Recipe_Observer_and_Sentry_Wards,
         Item::Recipe_Observer_and_Sentry_Wards},
        {(int)Item::Observer_and_Sentry_Wards, Item::Observer_and_Sentry_Wards},
        {(int)Item::Recipe_Boots_of_Travel2, Item::Recipe_Boots_of_Travel2},
        {(int)Item::Boots_of_Travel2, Item::Boots_of_Travel2},
        {(int)Item::Recipe_Lotus_Orb, Item::Recipe_Lotus_Orb},
        {(int)Item::Lotus_Orb, Item::Lotus_Orb},
        {(int)Item::Recipe_Solar_Crest, Item::Recipe_Solar_Crest},
        {(int)Item::Recipe_Octarine_Core, Item::Recipe_Octarine_Core},
        {(int)Item::Solar_Crest, Item::Solar_Crest},
        {(int)Item::Recipe_Guardian_Greaves, Item::Recipe_Guardian_Greaves},
        {(int)Item::Guardian_Greaves, Item::Guardian_Greaves},
        {(int)Item::Aether_Lens, Item::Aether_Lens},
        {(int)Item::Recipe_Aether_Lens, Item::Recipe_Aether_Lens},
        {(int)Item::Recipe_Dragon_Lance, Item::Recipe_Dragon_Lance},
        {(int)Item::Octarine_Core, Item::Octarine_Core},
        {(int)Item::Dragon_Lance, Item::Dragon_Lance},
        {(int)Item::Faerie_Fire, Item::Faerie_Fire},
        {(int)Item::Recipe_Iron_Talon, Item::Recipe_Iron_Talon},
        {(int)Item::Iron_Talon, Item::Iron_Talon},
        {(int)Item::Tango_Shared, Item::Tango_Shared},
        {(int)Item::Crimson_Guard, Item::Crimson_Guard},
        {(int)Item::Recipe_Crimson_Guard, Item::Recipe_Crimson_Guard},
        {(int)Item::Recipe_Moon_Shard, Item::Recipe_Moon_Shard},
        {(int)Item::Moon_Shard, Item::Moon_Shard},
        {(int)Item::Recipe_Silver_Edge, Item::Recipe_Silver_Edge},
        {(int)Item::Silver_Edge, Item::Silver_Edge},
        {(int)Item::Recipe_Glimmer_Cape, Item::Recipe_Glimmer_Cape},
        {(int)Item::Glimmer_Cape, Item::Glimmer_Cape},
        {(int)Item::Greevil_Taffy, Item::Greevil_Taffy},
        {(int)Item::DOTA_Tooltip_Ability_item_mystery_hook,
         Item::DOTA_Tooltip_Ability_item_mystery_hook},
        {(int)Item::DOTA_Tooltip_Ability_item_mystery_arrow,
         Item::DOTA_Tooltip_Ability_item_mystery_arrow},
        {(int)Item::DOTA_Tooltip_Ability_item_mystery_missile,
         Item::DOTA_Tooltip_Ability_item_mystery_missile},
        {(int)Item::DOTA_Tooltip_Ability_item_mystery_toss,
         Item::DOTA_Tooltip_Ability_item_mystery_toss},
        {(int)Item::DOTA_Tooltip_Ability_item_mystery_vacuum,
         Item::DOTA_Tooltip_Ability_item_mystery_vacuum},
        {(int)Item::DOTA_Tooltip_Ability_item_halloween_rapier,
         Item::DOTA_Tooltip_Ability_item_halloween_rapier},
        {(int)Item::Greevil_Whistle, Item::Greevil_Whistle},
        {(int)Item::Greevil_Whistle2, Item::Greevil_Whistle2},
        {(int)Item::A_Gift, Item::A_Gift},
        {(int)Item::Xmas_Stocking, Item::Xmas_Stocking},
        {(int)Item::Speed_Skates, Item::Speed_Skates},
        {(int)Item::Fruit_bit_Cake, Item::Fruit_bit_Cake},
        {(int)Item::Wizard_Cookie, Item::Wizard_Cookie},
        {(int)Item::Cocoa_with_Marshmallows, Item::Cocoa_with_Marshmallows},
        {(int)Item::Clove_Studded_Ham, Item::Clove_Studded_Ham},
        {(int)Item::Kringle, Item::Kringle},
        {(int)Item::Snow_Mushroom, Item::Snow_Mushroom},
        {(int)Item::Greevil_Treat, Item::Greevil_Treat},
        {(int)Item::Greevil_Chow, Item::Greevil_Chow},
        {(int)Item::Greevil_Blink_Bone, Item::Greevil_Blink_Bone},
    });
    const std::map<Item, std::string> itemNames({
        {Item::Unknown, "Unknown"},
        {Item::Blink_Dagger, "Blink Dagger"},
        {Item::Blades_of_Attack, "Blades of Attack"},
        {Item::Broadsword, "Broadsword"},
        {Item::Chainmail, "Chainmail"},
        {Item::Claymore, "Claymore"},
        {Item::Helm_of_Iron_Will, "Helm of Iron Will"},
        {Item::Javelin, "Javelin"},
        {Item::Mithril_Hammer, "Mithril Hammer"},
        {Item::Platemail, "Platemail"},
        {Item::Quarterstaff, "Quarterstaff"},
        {Item::Quelling_Blade, "Quelling Blade"},
        {Item::Ring_of_Protection, "Ring of Protection"},
        {Item::Gauntlets_of_Strength, "Gauntlets of Strength"},
        {Item::Slippers_of_Agility, "Slippers of Agility"},
        {Item::Mantle_of_Intelligence, "Mantle of Intelligence"},
        {Item::Iron_Branch, "Iron Branch"},
        {Item::Belt_of_Strength, "Belt of Strength"},
        {Item::Band_of_Elvenskin, "Band of Elvenskin"},
        {Item::Robe_of_the_Magi, "Robe of the Magi"},
        {Item::Circlet, "Circlet"},
        {Item::Ogre_Club, "Ogre Club"},
        {Item::Blade_of_Alacrity, "Blade of Alacrity"},
        {Item::Staff_of_Wizardry, "Staff of Wizardry"},
        {Item::Ultimate_Orb, "Ultimate Orb"},
        {Item::Gloves_of_Haste, "Gloves of Haste"},
        {Item::Morbid_Mask, "Morbid Mask"},
        {Item::Ring_of_Regen, "Ring of Regen"},
        {Item::Sages_Mask, "Sage's Mask"},
        {Item::Boots_of_Speed, "Boots of Speed"},
        {Item::Gem_of_True_Sight, "Gem of True Sight"},
        {Item::Cloak, "Cloak"},
        {Item::Talisman_of_Evasion, "Talisman of Evasion"},
        {Item::Cheese, "Cheese"},
        {Item::Magic_Stick, "Magic Stick"},
        {Item::Recipe_Magic_Wand, "Recipe: Magic Wand"},
        {Item::Magic_Wand, "Magic Wand"},
        {Item::Ghost_Scepter, "Ghost Scepter"},
        {Item::Clarity, "Clarity"},
        {Item::Healing_Salve, "Healing Salve"},
        {Item::Dust_of_Appearance, "Dust of Appearance"},
        {Item::Bottle, "Bottle"},
        {Item::Observer_Ward, "Observer Ward"},
        {Item::Sentry_Ward, "Sentry Ward"},
        {Item::Tango, "Tango"},
        {Item::Animal_Courier, "Animal Courier"},
        {Item::Town_Portal_Scroll, "Town Portal Scroll"},
        {Item::Recipe_Boots_of_Travel, "Recipe: Boots of Travel"},
        {Item::Boots_of_Travel, "Boots of Travel"},
        {Item::Recipe_Phase_Boots, "Recipe: Phase Boots"},
        {Item::Phase_Boots, "Phase Boots"},
        {Item::Demon_Edge, "Demon Edge"},
        {Item::Eaglesong, "Eaglesong"},
        {Item::Reaver, "Reaver"},
        {Item::Sacred_Relic, "Sacred Relic"},
        {Item::Hyperstone, "Hyperstone"},
        {Item::Ring_of_Health, "Ring of Health"},
        {Item::Void_Stone, "Void Stone"},
        {Item::Mystic_Staff, "Mystic Staff"},
        {Item::Energy_Booster, "Energy Booster"},
        {Item::Point_Booster, "Point Booster"},
        {Item::Vitality_Booster, "Vitality Booster"},
        {Item::Recipe_Power_Treads, "Recipe: Power Treads"},
        {Item::Power_Treads, "Power Treads"},
        {Item::Recipe_Hand_of_Midas, "Recipe: Hand of Midas"},
        {Item::Hand_of_Midas, "Hand of Midas"},
        {Item::Recipe_Oblivion_Staff, "Recipe: Oblivion Staff"},
        {Item::Oblivion_Staff, "Oblivion Staff"},
        {Item::Recipe_Perseverance, "Recipe: Perseverance"},
        {Item::Perseverance, "Perseverance"},
        {Item::Recipe_Poor_Mans_Shield, "Recipe: Poor Man's Shield"},
        {Item::Poor_Mans_Shield, "Poor Man's Shield"},
        {Item::Recipe_Bracer, "Recipe: Bracer"},
        {Item::Bracer, "Bracer"},
        {Item::Recipe_Wraith_Band, "Recipe: Wraith Band"},
        {Item::Wraith_Band, "Wraith Band"},
        {Item::Recipe_Null_Talisman, "Recipe: Null Talisman"},
        {Item::Null_Talisman, "Null Talisman"},
        {Item::Recipe_Mekansm, "Recipe: Mekansm"},
        {Item::Mekansm, "Mekansm"},
        {Item::Recipe_Vladmirs_Offering, "Recipe: Vladmir's Offering"},
        {Item::Vladmirs_Offering, "Vladmir's Offering"},
        {Item::Flying_Courier, "Flying Courier"},
        {Item::Recipe_Buckler, "Recipe: Buckler"},
        {Item::Buckler, "Buckler"},
        {Item::Recipe_Ring_of_Basilius, "Recipe: Ring of Basilius"},
        {Item::Ring_of_Basilius, "Ring of Basilius"},
        {Item::Recipe_Pipe_of_Insight, "Recipe: Pipe of Insight"},
        {Item::Pipe_of_Insight, "Pipe of Insight"},
        {Item::Recipe_Urn_of_Shadows, "Recipe: Urn of Shadows"},
        {Item::Urn_of_Shadows, "Urn of Shadows"},
        {Item::Recipe_Headdress, "Recipe: Headdress"},
        {Item::Headdress, "Headdress"},
        {Item::Recipe_Scythe_of_Vyse, "Recipe: Scythe of Vyse"},
        {Item::Scythe_of_Vyse, "Scythe of Vyse"},
        {Item::Recipe_Orchid_Malevolence, "Recipe: Orchid Malevolence"},
        {Item::Orchid_Malevolence, "Orchid Malevolence"},
        {Item::Recipe_Euls_Scepter_of_Divinity,
         "Recipe: Eul's Scepter of Divinity"},
        {Item::Euls_Scepter_of_Divinity, "Eul's Scepter of Divinity"},
        {Item::Recipe_Force_Staff, "Recipe: Force Staff"},
        {Item::Force_Staff, "Force Staff"},
        {Item::Recipe_Dagon, "Recipe: Dagon"},
        {Item::Dagon, "Dagon"},
        {Item::Recipe_Necronomicon, "Recipe: Necronomicon"},
        {Item::Necronomicon, "Necronomicon"},
        {Item::Recipe_Aghanims_Scepter, "Recipe: Aghanim's Scepter"},
        {Item::Aghanims_Scepter, "Aghanim's Scepter"},
        {Item::Recipe_Refresher_Orb, "Recipe: Refresher Orb"},
        {Item::Refresher_Orb, "Refresher Orb"},
        {Item::Recipe_Assault_Cuirass, "Recipe: Assault Cuirass"},
        {Item::Assault_Cuirass, "Assault Cuirass"},
        {Item::Recipe_Heart_of_Tarrasque, "Recipe: Heart of Tarrasque"},
        {Item::Heart_of_Tarrasque, "Heart of Tarrasque"},
        {Item::Recipe_Black_King_Bar, "Recipe: Black King Bar"},
        {Item::Black_King_Bar, "Black King Bar"},
        {Item::Aegis_of_the_Immortal, "Aegis of the Immortal"},
        {Item::Recipe_Shivas_Guard, "Recipe: Shiva's Guard"},
        {Item::Shivas_Guard, "Shiva's Guard"},
        {Item::Recipe_Bloodstone, "Recipe: Bloodstone"},
        {Item::Bloodstone, "Bloodstone"},
        {Item::Recipe_Linkens_Sphere, "Recipe: Linken's Sphere"},
        {Item::Linkens_Sphere, "Linken's Sphere"},
        {Item::Recipe_Vanguard, "Recipe: Vanguard"},
        {Item::Vanguard, "Vanguard"},
        {Item::Recipe_Blade_Mail, "Recipe: Blade Mail"},
        {Item::Blade_Mail, "Blade Mail"},
        {Item::Recipe_Soul_Booster, "Recipe: Soul Booster"},
        {Item::Soul_Booster, "Soul Booster"},
        {Item::Recipe_Hood_of_Defiance, "Recipe: Hood of Defiance"},
        {Item::Hood_of_Defiance, "Hood of Defiance"},
        {Item::Recipe_Divine_Rapier, "Recipe: Divine Rapier"},
        {Item::Divine_Rapier, "Divine Rapier"},
        {Item::Recipe_Monkey_King_Bar, "Recipe: Monkey King Bar"},
        {Item::Monkey_King_Bar, "Monkey King Bar"},
        {Item::Recipe_Radiance, "Recipe: Radiance"},
        {Item::Radiance, "Radiance"},
        {Item::Recipe_Butterfly, "Recipe: Butterfly"},
        {Item::Butterfly, "Butterfly"},
        {Item::Recipe_Daedalus, "Recipe: Daedalus"},
        {Item::Daedalus, "Daedalus"},
        {Item::Recipe_Skull_Basher, "Recipe: Skull Basher"},
        {Item::Skull_Basher, "Skull Basher"},
        {Item::Recipe_Battle_Fury, "Recipe: Battle Fury"},
        {Item::Battle_Fury, "Battle Fury"},
        {Item::Recipe_Manta_Style, "Recipe: Manta Style"},
        {Item::Manta_Style, "Manta Style"},
        {Item::Recipe_Crystalys, "Recipe: Crystalys"},
        {Item::Crystalys, "Crystalys"},
        {Item::Recipe_Armlet_of_Mordiggian, "Recipe: Armlet of Mordiggian"},
        {Item::Armlet_of_Mordiggian, "Armlet of Mordiggian"},
        {Item::Shadow_Blade, "Shadow Blade"},
        {Item::Recipe_Sange_and_Yasha, "Recipe: Sange and Yasha"},
        {Item::Sange_and_Yasha, "Sange and Yasha"},
        {Item::Recipe_Satanic, "Recipe: Satanic"},
        {Item::Satanic, "Satanic"},
        {Item::Recipe_Mjollnir, "Recipe: Mjollnir"},
        {Item::Mjollnir, "Mjollnir"},
        {Item::Recipe_Eye_of_Skadi, "Recipe: Eye of Skadi"},
        {Item::Eye_of_Skadi, "Eye of Skadi"},
        {Item::Recipe_Sange, "Recipe: Sange"},
        {Item::Sange, "Sange"},
        {Item::Recipe_Helm_of_the_Dominator, "Recipe: Helm of the Dominator"},
        {Item::Helm_of_the_Dominator, "Helm of the Dominator"},
        {Item::Recipe_Maelstrom, "Recipe: Maelstrom"},
        {Item::Maelstrom, "Maelstrom"},
        {Item::Recipe_Desolator, "Recipe: Desolator"},
        {Item::Desolator, "Desolator"},
        {Item::Recipe_Yasha, "Recipe: Yasha"},
        {Item::Yasha, "Yasha"},
        {Item::Recipe_Mask_of_Madness, "Recipe: Mask of Madness"},
        {Item::Mask_of_Madness, "Mask of Madness"},
        {Item::Recipe_Diffusal_Blade, "Recipe: Diffusal Blade"},
        {Item::Diffusal_Blade, "Diffusal Blade"},
        {Item::Recipe_Ethereal_Blade, "Recipe: Ethereal Blade"},
        {Item::Ethereal_Blade, "Ethereal Blade"},
        {Item::Recipe_Soul_Ring, "Recipe: Soul Ring"},
        {Item::Soul_Ring, "Soul Ring"},
        {Item::Recipe_Arcane_Boots, "Recipe: Arcane Boots"},
        {Item::Arcane_Boots, "Arcane Boots"},
        {Item::Orb_of_Venom, "Orb of Venom"},
        {Item::Stout_Shield, "Stout Shield"},
        {Item::Recipe_Shadow_Blade, "Recipe: Shadow Blade"},
        {Item::Recipe_Drum_of_Endurance, "Recipe: Drum of Endurance"},
        {Item::Drum_of_Endurance, "Drum of Endurance"},
        {Item::Recipe_Medallion_of_Courage, "Recipe: Medallion of Courage"},
        {Item::Medallion_of_Courage, "Medallion of Courage"},
        {Item::Smoke_of_Deceit, "Smoke of Deceit"},
        {Item::Recipe_Veil_of_Discord, "Recipe: Veil of Discord"},
        {Item::Veil_of_Discord, "Veil of Discord"},
        {Item::Recipe_Necronomicon2, "Recipe: Necronomicon"},
        {Item::Recipe_Necronomicon3, "Recipe: Necronomicon"},
        {Item::Necronomicon2, "Necronomicon"},
        {Item::Necronomicon3, "Necronomicon"},
        {Item::Recipe_Diffusal_Blade2, "Recipe: Diffusal Blade"},
        {Item::Diffusal_Blade2, "Diffusal Blade"},
        {Item::Recipe_Dagon2, "Recipe: Dagon"},
        {Item::Recipe_Dagon3, "Recipe: Dagon"},
        {Item::Recipe_Dagon4, "Recipe: Dagon"},
        {Item::Recipe_Dagon5, "Recipe: Dagon"},
        {Item::Dagon2, "Dagon"},
        {Item::Dagon3, "Dagon"},
        {Item::Dagon4, "Dagon"},
        {Item::Dagon5, "Dagon"},
        {Item::Recipe_Rod_of_Atos, "Recipe: Rod of Atos"},
        {Item::Rod_of_Atos, "Rod of Atos"},
        {Item::Recipe_Abyssal_Blade, "Recipe: Abyssal Blade"},
        {Item::Abyssal_Blade, "Abyssal Blade"},
        {Item::Recipe_Heavens_Halberd, "Recipe: Heaven's Halberd"},
        {Item::Heavens_Halberd, "Heaven's Halberd"},
        {Item::Recipe_Ring_of_Aquila, "Recipe: Ring of Aquila"},
        {Item::Ring_of_Aquila, "Ring of Aquila"},
        {Item::Recipe_Tranquil_Boots, "Recipe: Tranquil Boots"},
        {Item::Tranquil_Boots, "Tranquil Boots"},
        {Item::Shadow_Amulet, "Shadow Amulet"},
        {Item::Enchanted_Mango, "Enchanted Mango"},
        {Item::Recipe_Observer_and_Sentry_Wards,
         "Recipe: Observer and Sentry Wards"},
        {Item::Observer_and_Sentry_Wards, "Observer and Sentry Wards"},
        {Item::Recipe_Boots_of_Travel2, "Recipe: Boots of Travel"},
        {Item::Boots_of_Travel2, "Boots of Travel"},
        {Item::Recipe_Lotus_Orb, "Recipe: Lotus Orb"},
        {Item::Lotus_Orb, "Lotus Orb"},
        {Item::Recipe_Solar_Crest, "Recipe: Solar Crest"},
        {Item::Recipe_Octarine_Core, "Recipe: Octarine Core"},
        {Item::Solar_Crest, "Solar Crest"},
        {Item::Recipe_Guardian_Greaves, "Recipe: Guardian Greaves"},
        {Item::Guardian_Greaves, "Guardian Greaves"},
        {Item::Aether_Lens, "Aether Lens"},
        {Item::Recipe_Aether_Lens, "Recipe: Aether Lens"},
        {Item::Recipe_Dragon_Lance, "Recipe: Dragon Lance"},
        {Item::Octarine_Core, "Octarine Core"},
        {Item::Dragon_Lance, "Dragon Lance"},
        {Item::Faerie_Fire, "Faerie Fire"},
        {Item::Recipe_Iron_Talon, "Recipe: Iron Talon"},
        {Item::Iron_Talon, "Iron Talon"},
        {Item::Tango_Shared, "Tango (Shared)"},
        {Item::Crimson_Guard, "Crimson Guard"},
        {Item::Recipe_Crimson_Guard, "Recipe: Crimson Guard"},
        {Item::Recipe_Moon_Shard, "Recipe: Moon Shard"},
        {Item::Moon_Shard, "Moon Shard"},
        {Item::Recipe_Silver_Edge, "Recipe: Silver Edge"},
        {Item::Silver_Edge, "Silver Edge"},
        {Item::Recipe_Glimmer_Cape, "Recipe: Glimmer Cape"},
        {Item::Glimmer_Cape, "Glimmer Cape"},
        {Item::Greevil_Taffy, "Greevil Taffy"},
        {Item::DOTA_Tooltip_Ability_item_mystery_hook,
         "DOTA_Tooltip_Ability_item_mystery_hook"},
        {Item::DOTA_Tooltip_Ability_item_mystery_arrow,
         "DOTA_Tooltip_Ability_item_mystery_arrow"},
        {Item::DOTA_Tooltip_Ability_item_mystery_missile,
         "DOTA_Tooltip_Ability_item_mystery_missile"},
        {Item::DOTA_Tooltip_Ability_item_mystery_toss,
         "DOTA_Tooltip_Ability_item_mystery_toss"},
        {Item::DOTA_Tooltip_Ability_item_mystery_vacuum,
         "DOTA_Tooltip_Ability_item_mystery_vacuum"},
        {Item::DOTA_Tooltip_Ability_item_halloween_rapier,
         "DOTA_Tooltip_Ability_item_halloween_rapier"},
        {Item::Greevil_Whistle, "Greevil Whistle"},
        {Item::Greevil_Whistle2, "Greevil Whistle"},
        {Item::A_Gift, "A Gift!"},
        {Item::Xmas_Stocking, "Xmas Stocking"},
        {Item::Speed_Skates, "Speed Skates"},
        {Item::Fruit_bit_Cake, "Fruit-bit Cake"},
        {Item::Wizard_Cookie, "Wizard Cookie"},
        {Item::Cocoa_with_Marshmallows, "Cocoa with Marshmallows"},
        {Item::Clove_Studded_Ham, "Clove Studded Ham"},
        {Item::Kringle, "Kringle"},
        {Item::Snow_Mushroom, "Snow Mushroom"},
        {Item::Greevil_Treat, "Greevil Treat"},
        {Item::Greevil_Chow, "Greevil Chow"},
        {Item::Greevil_Blink_Bone, "Greevil Blink Bone"},
    });
    inline Item itemFromInt(int item)
    {
        const auto iter = items.find(item);

        if(iter == items.end())
            return Item::Unknown;

        return iter->second;
    }

    inline std::string itemToString(Item item)
    {
        const auto iter = itemNames.find(item);

        if(iter == itemNames.end())
            return itemNames.at(Item::Unknown);

        return iter->second;
    }
} // namespace dota2
#endif // ifndef ITEMS_HPP_GENERATED
